/**
 * Pre-rendered food plates for the QR posters. Client-safe.
 *
 * A design's food — up to 17 dish photos, each with its own shadow — is the
 * same for every store, so it is drawn ONCE, at build time, into a transparent
 * WebP "plate" per design (owner's idea, 2026-10-03). A poster is then the
 * plate plus what differs per store: background, accent shapes, the store
 * name and the QR. One download instead of up to 27, and none of the 27
 * shadow blurs on the phone: on 2026-10-03 a single failed dish download was
 * enough to fail the whole poster.
 *
 * Plates: public/poster-art/plates/, generated by scripts/poster-plates/
 * (`npm run posters:plates`) with the same drawImageElement the renderer used,
 * in headless Chromium. tests/acceptance/poster-resilience.test.ts fails if a
 * plate is missing or older than its design or art.
 */
import type { PosterDesign } from '@/lib/qr/posterDesigns';
import { PLATE_DATA } from '@/lib/qr/posterPlateData';

export interface PlateFile { scale: number; src: string }
export interface Plate { hash: string; files: PlateFile[] }

/** Bump when drawImageElement changes, so every plate must be regenerated. */
export const PLATE_RENDER_VERSION = 1;

export const POSTER_PLATES: Readonly<Record<string, Plate>> = PLATE_DATA;

/**
 * The smallest plate at least as sharp as the render needs (`renderScale` =
 * device px per design unit), or the sharpest there is. Null without a plate.
 */
export function plateFor(design: PosterDesign, renderScale: number): PlateFile | null {
    const files = [...(POSTER_PLATES[design.id]?.files ?? [])].sort((a, b) => a.scale - b.scale);
    if (files.length === 0) return null;
    return files.find(f => f.scale >= renderScale) ?? files[files.length - 1];
}

/** cyrb53: a small, stable string hash — no crypto needed in the browser. */
function cyrb53(str: string): string {
    let h1 = 0xdeadbeef, h2 = 0x41c6ce57;
    for (let i = 0; i < str.length; i++) {
        const ch = str.charCodeAt(i);
        h1 = Math.imul(h1 ^ ch, 2654435761);
        h2 = Math.imul(h2 ^ ch, 1597334677);
    }
    h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
    h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);
    return (4294967296 * (2097151 & h2) + (h1 >>> 0)).toString(16).padStart(14, '0');
}

/**
 * Everything a plate depends on: the drawing version, the design's food layers
 * (position, size, rotation, shadow) and each art file's content (`artHash`).
 */
export function plateHash(design: PosterDesign, artHash: (src: string) => string): string {
    const images = design.elements.filter(e => e.kind === 'image');
    const art = images.map(e => (e.kind === 'image' ? artHash(e.src) : ''));
    return cyrb53(JSON.stringify({ v: PLATE_RENDER_VERSION, images, art }));
}
