// GENERATED by scripts/poster-plates/generate.mjs — run `npm run posters:plates`.
// Do not edit by hand.
import type { Plate } from '@/lib/qr/posterPlates';

export const PLATE_DATA: Record<string, Plate> = {
    "feast-ring": {
        "hash": "035f0264c2732a",
        "files": [
            {
                "scale": 2,
                "src": "/poster-art/plates/feast-ring@2x-035f0264c2.webp"
            },
            {
                "scale": 4,
                "src": "/poster-art/plates/feast-ring@4x-035f0264c2.webp"
            }
        ]
    },
    "table-edge": {
        "hash": "0c03d5388d7565",
        "files": [
            {
                "scale": 2,
                "src": "/poster-art/plates/table-edge@2x-0c03d5388d.webp"
            },
            {
                "scale": 4,
                "src": "/poster-art/plates/table-edge@4x-0c03d5388d.webp"
            }
        ]
    },
    "cafe-floating": {
        "hash": "06ce870372679b",
        "files": [
            {
                "scale": 2,
                "src": "/poster-art/plates/cafe-floating@2x-06ce870372.webp"
            },
            {
                "scale": 4,
                "src": "/poster-art/plates/cafe-floating@4x-06ce870372.webp"
            }
        ]
    },
    "cafe-counter": {
        "hash": "03d414be9a9bfa",
        "files": [
            {
                "scale": 2,
                "src": "/poster-art/plates/cafe-counter@2x-03d414be9a.webp"
            },
            {
                "scale": 4,
                "src": "/poster-art/plates/cafe-counter@4x-03d414be9a.webp"
            }
        ]
    }
};
